[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs", "npm"]

[phases.build]
cmds = ["composer install --no-dev --no-interaction", "npm install", "npm run build"]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"