[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs", "npm"]

[phases.install]
cmds = ["composer install --no-dev --no-interaction", "npm install"]

[phases.build]
# On force le succès même si une commande de cache invisible tente de s'exécuter
cmds = ["npm run build", "echo 'Build CSS/JS terminé'"]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"